version: '3'

services:
  postgres:
      container_name: postgres
      image: postgres
      env_file:
        - ./code/Python/.env
      ports:
        - "5433:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
  jupyter:
    platform: linux/x86_64
    build: .
    image: takyam15/py-r-cheminfo:latest
    container_name: jupyter
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./code:/work/code
    tty: true
    stdin_open: true

volumes:
  pg_data:
